title: Talk with Westley
email: wes@wessence.com
description: Angličtina není jen o gramatice. Jde o sebevědomí.
url: "https://talkwithwestley.com"
baseurl: ""

author: 
  name: Westley Overcash
  twitter: westleyovercash

image: /assets/css/images/westley-overcash-talk-with-westley-ucitel-anglicky.jpg

timezone: Europe/Prague
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
