title: Westley Overcash
email: wes@wessence.com
description: Westley Overcash je jazykový mentor, který nabízí individuální lekce angličtiny zaměřené na sebevědomou komunikaci, jasné vyjadřování a praktické dovednosti pro skutečné situace.
url: "https://westleyovercash.github.io"
baseurl: "/talkwithwestley"
author:
  name: Westley Overcash
image: "assets/images/westley-overcash-talk-with-westley-ucitel-anglicky.jpg"
timezone: Europe/Prague
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
